arcus-azure/arcus.templates

- src/Arcus.Template.WebApi/Startup.cs
> FEAT: only allow 'JsonInputFormatter'

- src/Arcus.Template.WebApi/Startup.cs
> FEAT: add health check via middleware

- src/Arcus.Template.WebApi/Arcus.Template.WebApi.csproj
- src/Arcus.Template.WebApi/Program.cs
> FEAT: add console logging as default logger

- src/Arcus.Template.WebApi/.template.config/template.json
- src/Arcus.Template.WebApi/Arcus.Template.WebApi.csproj
- src/Arcus.Template.WebApi/Startup.cs
> FEAT: add SharedAccessKey as authentication option in the API template

- README.md
> Add NuGet badge to README

- README.md
- docs/features/web-api-template.md
> Provide better README

- build/nuget-release.yml
Correctly define the version for NuGet package
> Correctly define the version for NuGet package

- src/Arcus.Templates.WebApi/Startup.cs
> FIX: update Swagger UI doc file with 'Templates' i.o. 'Template'

- build/nuget-release.yml
GitHub Releases - Fix broken link to NuGet package
> GitHub Releases - Fix broken link

- docs/features/web-api-template.md
- Swagger is only available locally, not in PROD
- Simplify health check info
> Docs - Streamline Web API features

- docs/features/web-api-template.md
- src/Arcus.Templates.Tests.Integration/Security/v1/SecurityHeaderTests.cs
- src/Arcus.Templates.WebApi/Program.cs
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Closes #51
> Remove 'Server' header from web API template

- src/Arcus.Templates.Tests.Integration/Authentication/v1/SharedAccessKeyAuthenticationOptionTests.cs
- src/Arcus.Templates.Tests.Integration/Fixture/EndpointService.cs
- src/Arcus.Templates.Tests.Integration/Fixture/WebApiProject.cs
- src/Arcus.Templates.Tests.Integration/Health/HealthEndpointService.cs
- src/Arcus.Templates.Tests.Integration/Health/v1/HealthDockerEndpointTests.cs
- src/Arcus.Templates.Tests.Integration/Health/v1/HealthEndpointTests.cs
- src/Arcus.Templates.Tests.Integration/Security/v1/SecurityHeaderTests.cs
- src/Arcus.Templates.Tests.Integration/Swagger/SwaggerEndpointService.cs
- src/Arcus.Templates.Tests.Integration/Swagger/v1/SwaggerDocAvailabilityTests.cs
- src/Arcus.Templates.Tests.Integration/TestCollections.cs
- src/Arcus.Templates.Tests.Integration/TestTraits.cs
- src/Arcus.Templates.WebApi/Program.cs
Adds integration tests to check if the Swagger UI and Docs are only available in a Debug/DEV environment and hidden from a Release/PROD environment.
Closes #43
> TEST: add integration tests for Swagger UI/Docs

- docs/features/web-api-template.md
- src/Arcus.Templates.Tests.Integration/WebApi/Correlation/v1/CorrelationHeadersTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.WebApi/.template.config/template.json
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Startup.cs
Includes the correlation out-of-the-box and provide an project option to opt-out.
Closes #30
> FEAT: add correlation out-of-the-box in web API project template

- src/Arcus.Templates.Tests.Integration/WebApi/Correlation/v1/CorrelationHeadersTests.cs
> FIX: remove leftover teardown setting

- README.md
> DOCS: update README with Service Bus worker project template

- build/ci-build.yml
- build/nuget-release.yml
- build/templates/docker-integration-tests.yml
> CHORE: move integration tests to stage templates

- README.md
- docs/features/servicebus-topic-worker-template.md
- docs/index.md
> DOCS: add docs for Azure ServiceBus Topic project template

- build/ci-build.yml
- build/nuget-release.yml
- build/templates/docker-integration-tests.yml
- docs/features/servicebus-queue-worker-template.md
- docs/features/servicebus-topic-worker-template.md
- docs/features/web-api-template.md
- src/Arcus.Templates.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/Fixture/CommandArgument.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TestConfig.cs
- src/Arcus.Templates.Tests.Integration/Worker/Health/TcpHealthDockerProbeTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/Logging/ExcludeSerilogOptionTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProjectOptions.cs
- src/Arcus.Templates.Tests.Integration/appsettings.json
- Added option to both worker template proejct
- Added tests to probe the health when the option is selected
- Added feature/config docs for both template projects
Closes #84
> FEAT: provide an project option to exclude the Serilog logging from the worker projects

- build/ci-build.yml
- build/nuget-release.yml
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Dockerfile
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Dockerfile
- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.Tests.Integration/Fixture/TargetFramework.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
Updates the worker template projects to .NET Core 3.1.
Closes #88
> CHORE: update worker template projects from .NET Core 3.0 > 3.1

- build/ci-build.yml
- build/nuget-release.yml
- docs/features/web-api-template.md
- src/Arcus.Templates.Tests.Integration/Fixture/TargetFramework.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TestConfig.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Health/v1/HealthDockerEndpointTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Health/v1/HealthEndpointTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Health/v1/TimeSpanConverter.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Swagger/SwaggerEndpointService.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Dockerfile
- src/Arcus.Templates.WebApi/Program.cs
- src/Arcus.Templates.WebApi/Startup.cs
Update the web API project template with .NET Core 3.1 SDK.
Closes #87
> CHORE: update web API project template .NET Core 2.2 > 3.1

- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Startup.cs
> CHORE: update web API projecte template with updated correlation package

- build/nuget-release.yml
Relates to https://github.com/arcus-azure/azure-devops-templates/issues/34
> Chore - remove pre-release

- build/ci-build.yml
- build/nuget-release.yml
- build/templates/docker-integration-tests.yml
- build/templates/run-new-project-from-template.yml
- build/variables/build.yml
- build/variables/test.yml
- src/Arcus.Templates.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/OrdersMessagePump.cs
- src/Arcus.Templates.Tests.Integration/Worker/MessagePump/MessagePumpService.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBus/ServiceBusQueueMessagePumpTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBus/ServiceBusTopicMessagePumpTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.WebApi/.template.config/template.json
Relates to https://github.com/arcus-azure/arcus/issues/46
Closes #107
> Chore - move build & test variables to variable template

- build/nuget-release.yml
> Fix dependsOn for release

- build/ci-build.yml
- build/nuget-release.yml
- src/Arcus.Templates.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.WebApi/.template.config/template.json
> Chore - set package version in package template name

- src/Arcus.Templates.WebApi/Startup.cs
> Specify that endpoints should all be in lowercase

- build/nuget-release.yml
- docs/features/servicebus-queue-worker-template.md
- docs/features/servicebus-topic-worker-template.md
- docs/features/web-api-template.md
- docs/v0.1/features/web-api-template.md
> Docs - split template features by version

- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.Tests.Integration/WebApi/Swagger/v1/SwaggerDocCorrelationHeadersTests.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Controllers/HealthController.cs
- src/Arcus.Templates.WebApi/Startup.cs
> Feature - add OpenApi documentation for the Correlation headers

- src/Arcus.Templates.Tests.Integration/WebApi/Authentication/v1/CertificateAuthenticationOptionTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Authentication/v1/JwtAuthenticationOptionTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Authentication/v1/SharedAccessKeyAuthenticationOptionTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Startup.cs
> Feature - add OpenApi security definitions for authentication mechanisms

- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Logging/v1/LoggingOptionTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Startup.cs
- src/Arcus.Templates.WebApi/appsettings.json
> Feature - use Arcus.Observability Application Insights sink

- docs/v0.2/features/servicebus-queue-worker-template.md
- docs/v0.2/features/servicebus-topic-worker-template.md
- docs/v0.2/features/web-api-template.md
> Docs - update to v3 docs

- docs/preview/features/web-api-template.md
- src/Arcus.Templates.WebApi/.template.config/template.json
> Feature - use Serilog as default logging mechanism

- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
> Chore - use Observability.Telemetry.Core w/ Serilog

- renovate.json
Relates to https://github.com/arcus-azure/arcus/issues/117
> Fix - remove PR rebase option during Renovation

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.Http/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.WebApi/.template.config/template.json
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Provide improved classifications to align with existing ones.
> Provide improved classifications

- src/Arcus.Templates.AzureFunctions.Http/HttpBasedAzureFunction.cs
- src/Arcus.Templates.WebApi/Startup.cs
Some JSON serialization settings that were present in the Azure Functions HTTP trigger, but not in the web API.
> Feature - small JSON serialization improvements

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
Ignore warnings we introduce ourselves to inform the consumer + packaging warnings (see https://github.com/arcus-azure/arcus/issues/134)
> fix: expected project warnings

- src/Arcus.Templates.ServiceBus.Queue/Dockerfile
- src/Arcus.Templates.ServiceBus.Topic/Dockerfile
- src/Arcus.Templates.WebApi/Dockerfile
Upgrade web API, Queue, and Topic project templates.
> fix: manually upgrade docker images

- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/MetricReporting/DatabricksMetricReportingTests.cs
Creating temporary Databricks job so it don't impact existing test runs.
Closes #460
> test: improve databricks parallel test runs

- docs/preview/web-api-template.md
- src/Arcus.Templates.Tests.Integration/WebApi/Swagger/v1/SwaggerDocAvailabilityTests.cs
- src/Arcus.Templates.WebApi/Program.cs
Expose OpenAPI by default and provide a warning both in source and docs.
Closes #483
> feat: expose openapi by default w warning

- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Program.cs
Updates the Web API project template to use the recently Arcus packages that supports .NET 6.
> chore: update webapi template towards net6.0 arcus packages

- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Dockerfile
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Dockerfile
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
Upgrades Azure Service Bus topic & queue worker project templates towards .NET 6.
Closes #473
Closes #474
> feat: upgrade worker proj templates to net6.0

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/HttpBasedAzureFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.Tests.Integration/WebApi/Fixture/SelfSignedCertificate.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
Treat warnings as errors in the project template projects.
Relates to https://github.com/arcus-azure/arcus/issues/196
> chore: treat warnings as errors

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Startup.cs
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Startup.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Startup.cs
- src/Arcus.Templates.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/Fixture/ProjectOptions.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Configuration/AppSettingsProjectCombinationTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Logging/v1/LoggingOptionTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.WebApi/Program.cs
- src/Arcus.Templates.WebApi/appsettings.json
Only add an Azure Application Insights instrumentation key if such value is present.
Closes #563
> feat: only add existing app insights instrumentation key

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
Adds package readme project tag to project files.
Relates to https://github.com/arcus-azure/arcus/issues/209
> chore: add package readme project tag

- src/Arcus.Templates.WebApi/appsettings.json
WebApi template improvement: add APPINSIGHTS_INSTRUMENTATIONKEY to appsettings.json
Closes #602
> feat: add empty APPINSIGHTS_INSTRUMENTATIONKEY to appsettings.json

- build/templates/docker-integration-tests.yml
- src/Arcus.Templates.Tests.Integration/Fixture/ApplicationInsightsTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Logging/v1/RequestTrackingTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Swagger/v1/SwaggerDocCorrelationHeadersTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProject.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Controllers/HealthController.cs
- src/Arcus.Templates.WebApi/Program.cs
- src/Arcus.Templates.WebApi/appsettings.json
Use the newest features in observability and web API in the Web API project template.
Relates to #620
> feat: use newest features in observability/webapi

- src/Arcus.Templates.AzureFunctions.Http/HttpCorrelationOpenApiResponseHeaders.cs
- src/Arcus.Templates.WebApi/Controllers/HealthController.cs
- src/Arcus.Templates.WebApi/Program.cs
Some correlation ID's were having wrong descriptions.
Fixed that.
> chore: fix open api descriptions

- docs/preview/index.md
Add simple introduction section on the index page.
Closes #679
> docs: add introduction page

- build/templates/docker-integration-tests.yml
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Program.cs
- src/Arcus.Templates.WebApi/Properties/launchSettings.json
Add `launchUrl` to `launchSettings.json` when OpenAPI is configured on the Web API project template.
Closes #694
> chore: add launchUrl to webapi project template

- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.Tests.Integration/AzureFunctions/EventHubs/AzureFunctionsEventHubsProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/ServiceBus/AzureFunctionsServiceBusProject.cs
- src/Arcus.Templates.Tests.Integration/Worker/EventHubsWorkerProject.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/OrderCreatedEvent.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/TestOrdersAzureEventHubsMessageHandler.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/TestOrdersAzureServiceBusMessageHandler.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/TestOrdersMessageHandler.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
Use Arcus EventGrid v3.3 for integration testing.
> chore: use eventgrid v3.3

- src/Arcus.Templates.AzureFunctions.Http/.template.config/template.json
- src/Arcus.Templates.WebApi/.template.config/template.json
> chore: Align template classifications with default .net templates

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/local.settings.json
- src/Arcus.Templates.AzureFunctions.EventHubs/local.settings.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/local.settings.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/local.settings.json
Add `local.settings.json` file with Azurite support for every Azure Functions project template.
Closes #782
> chore: add az func local settings

- docs/preview/features/azurefunctions-eventhubs-template.md
- docs/versioned_docs/version-v1.0.0/features/azurefunctions-eventhubs-template.md
- docs/versioned_docs/version-v1.1.0/features/azurefunctions-eventhubs-template.md
> fix: correct project alias for az func eventhubs project template

- src/Arcus.Templates.AzureFunctions.EventHubs/Arcus.Templates.AzureFunctions.EventHubs.csproj
- src/Arcus.Templates.AzureFunctions.EventHubs/Program.cs
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/Model/ApiHealthReport.cs
- src/Arcus.Templates.AzureFunctions.Http/Model/ApiHealthReportEntry.cs
- src/Arcus.Templates.AzureFunctions.Http/Model/Order.cs
- src/Arcus.Templates.AzureFunctions.Http/OpenApiConfigurationOptions.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.EventHubs/Arcus.Templates.EventHubs.csproj
- src/Arcus.Templates.EventHubs/Model/SensorReading.cs
- src/Arcus.Templates.EventHubs/Program.cs
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Models/ApiHealthReport.cs
- src/Arcus.Templates.WebApi/Models/ApiHealthReportEntry.cs
Use the `<nullable>true</nullable>` option in the projects, and fixes any possible `null` assignment.
Closes #865
> chore: use nullable option in project templates

- src/Arcus.Templates.AzureFunctions.EventHubs/Arcus.Templates.AzureFunctions.EventHubs.csproj
- src/Arcus.Templates.AzureFunctions.EventHubs/SensorReadingAzureEventHubsMessageHandler.cs
- src/Arcus.Templates.AzureFunctions.EventHubs/SensorReadingFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/HealthFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/OrderFunction.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/OrderFunction.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/OrdersAzureServiceBusMessageHandler.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/OrderFunction.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/OrdersAzureServiceBusMessageHandler.cs
- src/Arcus.Templates.EventHubs/Arcus.Templates.EventHubs.csproj
- src/Arcus.Templates.EventHubs/SensorReadingAzureEventHubsMessageHandler.cs
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Controllers/HealthController.cs
- src/Arcus.Templates.WebApi/Models/ApiHealthReport.cs
Update all Renovate NuGet package updates in one go.
> chore: update nuget packages
