- README.md
- docs/features/web-api-template.md
- docs/index.md
* Adds introduction page for the global 'arcus templates' project.
* Provide a simple structure of the current state of the web API project and the already available auth option.
Relates to #6 
Relates to #12
> DOC: add intro and web api feature documentation

- build/nuget-release.yml
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
> Build requires 'Package.Version', not 'Package.Version.ManualTrigger'

- README.md
- build/nuget-release.yml
- docs/features/web-api-template.md
- docs/index.md
- Use `dotnet new` example instead of `Install-Package` in GitHub release
- Use `--install` rather than `-i` to be more explicit
> Docs - Use "dotnet new" example in GitHub release

- src/Arcus.Templates.WebApi/Startup.cs
Adds the string enum converter to the JSON output formatter to change
the way enumerations are serialized in the response.
Closes #36
> FEAT: use string representation for enums instead of integers

- README.md
- docs/features/web-api-template.md
Use "dotnet new --name" instead of "dotnet new -n" to make it clear what it is for, not everybody knows this.
> Docs - Use "dotnet new --name" instead of "dotnet new -n"

- src/Arcus.Templates.Tests.Integration/Fixture/TearDownOptions.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TestConfig.cs
- src/Arcus.Templates.Tests.Integration/Fixture/WebApiProject.cs
Make the tear down in the disposing of the temporary project, created from a template, configurable.
This configuration consists now with three options:
* `KeepProjectDirectory`: which makes sure that the temp folder is not removed when the test is done.
* `KeepProjectRunning`: which makes sure that the temp project is still running when the test is done.
* `KeepProjectTemplateInstalled`: which makes sure that the template used in the test is still installed after the test is done.
> "With great strength comes great responsibility"
Closes #45
> FEAT: configurable project template teardown

- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Startup.cs
- Remove legacy for certificate auth
- Use latest versions of dependencies, include Arcus Web API
Closes #58
> Remove legacy for certificate auth & use latest versions of dependencies

- build/ci-build.yml
- src/Arcus.Templates.Tests.Integration/Authentication/v1/CertificateAuthenticationOptionTests.cs
- src/Arcus.Templates.Tests.Integration/Authentication/v1/SharedAccessKeyAuthenticationOptionTests.cs
Uses the integration test YAML template which takes in a category. This allows us to split the 'Docker' integration tests from the 'Self-Containing' integration tests; making our CI build more correctly representing the test targets.
Closes #46
> CHORE: introduce integration category for Docker & SelfContaining tests

- build/nuget-release.yml
NuGet: Use correct GitHub repo for pre-releases
> NuGet: Use correct GitHub repo for pre-releases

- docs/features/web-api-template.md
- src/Arcus.Templates.Tests.Integration/WebApi/Swagger/v1/SwaggerDocAvailabilityTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.WebApi/.template.config/template.json
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Startup.cs
Provide project option to opt-out of the OpenAPI Swagger docs and UI generation from XML docs.
Closes #82
> FEAT: provide opt-out of OpenApi docs with  project option

- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Dockerfile
- src/Arcus.Templates.ServiceBus.Topic/EmptyMessage.cs
- src/Arcus.Templates.ServiceBus.Topic/EmptyMessagePump.cs
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TestConfig.cs
- src/Arcus.Templates.Tests.Integration/Worker/Health/TcpHealthProbeTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/MessagePump/MessagePumpService.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBus/ServiceBusQueueMessagePumpTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBus/ServiceBusTopicMessagePumpTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusEntity.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.Tests.Integration/appsettings.json
- src/Arcus.Templates.sln
Provides a new project template `arcus-servicebus-topic` to create a project with a message pump on a Azure Service Bus Topic.
Relates to #11
> FEAT: add service bus topic project template

- src/Arcus.Templates.WebApi/Properties/launchSettings.json
- src/Arcus.Templates.WebApi/Startup.cs
> Fix - disable SSL in web API template to run Docker debug before HTTPS config

- src/Arcus.Templates.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.Tests.Integration/Fixture/InMemorySecretProvider.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProject.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Program.cs
- src/Arcus.Templates.WebApi/Startup.cs
Updates the web API template and both worker templates with using the secret stores instead of registering the `ISecretProvider` by themselves.
Plus add the `IConfiguration` to the stores when running in DEBUG.
Relates to #186
> Feature - introduce secret store concept into templates

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/.template.config/ide.host.json
- src/Arcus.Templates.AzureFunctions.Http/.template.config/ide.host.json
- src/Arcus.Templates.ServiceBus.Queue/.template.config/ide.host.json
- src/Arcus.Templates.ServiceBus.Topic/.template.config/ide.host.json
- src/Arcus.Templates.WebApi/.template.config/ide.host.json
Re-Closes #297 
Relates to #296
> Feature - remove the 'Arcus ...' prefix of the templates in VS

- docs/features/web-api-template.md
- docs/preview/web-api-template.md
- docs/v0.1/web-api-template.md
- docs/v0.2/web-api-template.md
- docs/v0.3/web-api-template.md
- docs/v0.6/web-api-template.md
We don't use this version badge anymore.
> Docs - remove unused version badge in web API feature docs

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Startup.cs
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/AzureFunctionsDatabricksProject.cs
- src/Arcus.Templates.Tests.Integration/WebApi/WebApiProjectOptions.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.WebApi/Program.cs
The project templates were using an 'old' and deprecated kickstart example, which is now updated to the most recent and recommended one.
Closes #318
> Feature - use current Azure Key Vault extension to kickstart in project templates 

- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/MetricReporting/DatabricksMetricReportingTests.cs
- src/Arcus.Templates.Tests.Integration/Fixture/ApplicationInsightsTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Logging/v1/RequestTrackingTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Logging/v1/SaboteurController.cs
- src/Arcus.Templates.WebApi/Startup.cs
Moved the exception handling after the request tracking and add a test that proves this.
The exception handling will therefore not handling exceptions from the routing and tracking and correlation but only for the processes that comes after.
Relates to https://github.com/arcus-azure/arcus.webapi/discussions/208
> fix: failed response request tracking

- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
Replace the Serilog debug logging with verbose logging to see more detailed error messages when the integration tests for on-the-fly generated projects based on our templates are failing.
> test: provide diagnostic error messages during integration tests

- src/Arcus.Templates.AzureFunctions.Http/HttpBasedAzureFunction.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Api/OrderService.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/AzureFunctionsHttpProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Fix/OrderBatchTests.cs
Use `JToken` to parse incoming HTTP request bodies so we can support JSON arrays.
Closes #330
> fix: support parsing of JSON arrays

- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
With the update of our new Arcus.Messaging package, we have limited the amount of dependencies and so, don't implicitly reference the hosting package anymore. Which is the reason why this update was failing.
> chore(deps): update with necessary host packages

- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/MetricReporting/DatabricksMetricReportingTests.cs
Don't ask me why, but apparently, the Databricks job takes longer now then before to complete. Maybe because the resource being used by other parties more? Don't know, actually. Let's hope it's more stable mow.
> test: increase Azure Databricks timeout

- src/Arcus.Templates.WebApi/.template.config/template.json
- src/Arcus.Templates.WebApi/Startup.cs
To reduce logs from Microsoft, we should set it to warning.
Closes #354
> fix: set Microsoft log level to warning

- src/Arcus.Templates.WebApi/Controllers/HealthController.cs
To minimize costs and logging noise, only track the health request when the response status code is in the range of 5xx.
Closes #353
> feat: only track health request when 5xx

- src/Arcus.Templates.Tests.Integration/Worker/Fixture/Customer.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/Order.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/OrderCreatedEvent.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/OrderCreatedEventData.cs
- src/Arcus.Templates.Tests.Integration/Worker/Fixture/OrdersMessageHandler.cs
- src/Arcus.Templates.Tests.Integration/Worker/MessagePump/MessagePumpService.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
Streamlining the type of messages with the messaging repo that are set on the queue will remove the problem when leftover messages result in 'unhandled messages' in the logs.
Makes it cleaner and more understabable.
> chore: streamline order events on az service bus

- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
Hi, I found a NU1608 warning in the Arcus.Templates.Tests.Integration.csproj:
`Warning NU1608 Detected package version outside of dependency constraint: Microsoft.Azure.ServiceBus 4.1.1 requires System.IdentityModel.Tokens.Jwt (>= 5.4.0 && < 6.0.0) but version System.IdentityModel.Tokens.Jwt 6.11.1 was resolved.`
This fix can remove the warning from Arcus.Templates's dependency graph.
Hope the PR can help you.
Best regards,
sucrose
> fix: Resolve a NU1608 warning in the Arcus.Templates.Tests.Integration.csproj

- docs/preview/azurefunctions-http-template.md
- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.Http/.template.config/ide.host.json
- src/Arcus.Templates.AzureFunctions.Http/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.Http/HealthFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/HttpBasedAzureFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/OrderFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/AzureFunctionsHttpProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/AzureFunctionsHttpProjectOptions.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Health/HealthChecksTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Health/HealthEndpointService.cs
Adds an project option `--include-healthchecks` to the Azure Functions HTTP trigger project template to include an Azure Functions that response with the current health status of the running Azure Function.
Closes #398 
Relates to #378
> feat: opt-in health checks for az func http trigger proj template

- build/templates/docker-integration-tests.yml
Use `ubuntu-latest` (via variable) in Docker integration tests.
https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-187-update#ubuntu-1604-will-be-removed-from-microsoft-hosted-pools-in-september-2021
> fix: use ubuntu-latest in docker tests

- build/templates/install-azure-functions-core-tools.yml
- src/Arcus.Templates.AzureFunctions.Http/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/Dockerfile
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/AzureFunctionsHttpProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Health/HealthChecksTests.cs
Upgrades the Azure Functions HTTP Trigger project template to .NET 6.
Closes #488
> feat: upgrade az func http trigger to net6.0

- src/Arcus.Templates.Tests.Integration/AzureFunctions/AzureFunctionsProject.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
Adds extra user-friendly exception message to inform users for possible missing tools or failures in the created test project based on the project template.
Closes #503
> chore: inform testers about az func tools

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Dockerfile
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/AzureFunctionsDatabricksProject.cs
Upgrade the Azure Functions Databricks JobMetrics project to .NET 6.
Relates to https://github.com/arcus-azure/arcus/issues/106
> chore: upgrade databricks jobmetrics to net6.0

- renovate.json
Update the Renovate configuration to ignore the `/docs` folder.
> chore: ignore `/docs` in Renovate config

- renovate.json
Ignoring the `/docs` folder in Renovate bot.
> chore: renovate ignore docs

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Startup.cs
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/AzureFunctionsProject.cs
Use 'APPINSIGHTS_INSTRUMENTATIONKEY' as environment variable to set instrumentation key.
Closes #547
Closes #528
> fix: use correct appinsights instrumentation key env var

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
Adds the GitHub README file to the NuGet package generation of the projects.
Adds feature docs project URL instead of GitHub URL to NuGet package.
Relates to arcus-azure/arcus#209
Relates to arcus-azure/arcus#208
> chore: add readme and proj url to nuget pkg

- src/Arcus.Templates.Tests.Integration/AzureFunctions/ServiceBus/Logging/SerilogLoggingTests.cs
Integration test had (still) an unnecessary tear down option set that was a left-over from local testing.
Follow-up of #578
> fix: remove unnecessary 'keep directory' tear down option

- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/.template.config/ide.host.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Startup.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/ServiceBus/AzureFunctionsServiceBusProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/ServiceBus/Logging/SerilogLoggingTests.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/ServiceBus/MessageHandling/OrderMessageHandlerTests.cs
Add project option to exclude Serilog logging from the Azure Functions Service Bus topic project temlate.
Closes #551
> feat: exclude serilog proj option for az func servicebus topic

- docs/preview/features/web-api-template.md
- src/Arcus.Templates.WebApi/Program.cs
Omit the default `/` route in the request tracking in the Web API project template.
Closes #537
> feat: omit default route in request tracking in web api template

- src/Arcus.Templates.WebApi/.template.config/template.json
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Controllers/HealthController.cs
- src/Arcus.Templates.WebApi/Program.cs
Use the user-friendly security authentication extensions instead of using the security filters themselves.
Closes #496
> feat: use webapi security extensions instead

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
Adds direct observability references to the project templates so that updates in observability results in quicker templates releases.
Closes #596
> chore: add direct observability references

- src/Arcus.Templates.AzureFunctions.Http/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/HealthFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/OrderFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Swagger/SwaggerOpenApiTests.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
The OpenApi functionality wasn't all excluded from the resulting project when using the `exclude-openApi` project option in the Azure Functions HTTP trigger project templates.
Closes #616
> bug: exclude openapi fully

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Startup.cs
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Startup.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Startup.cs
Add the RemoveMicrosoftApplicationInsightsLoggerProvider extension to all Serilog infrastructure code.
Closes #604 
Replaces: #607
> feat: Add the RemoveMicrosoftApplicationInsightsLoggerProvider extension to all Serilog infrastructure code

- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/HttpBasedAzureFunction.cs
- src/Arcus.Templates.AzureFunctions.Http/OrderFunction.cs
- src/Arcus.Templates.Tests.Integration/Arcus.Templates.Tests.Integration.csproj
Tracks the incoming HTTP request in the Azure Functions HTTP trigger project template. It uses a simple trick to enable service-to-service correlation by enriching the telemetry context with the correlation information instead of a dedicated Serilog enricher.
Closes #612
> feat: track http request in az func http trigger

- build/templates/docker-integration-tests.yml
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProjectOptions.cs
Uses Observability v2.5 in both Azure Service Bus .NET Worker project templates.
* Uses Application Insights connection string instead of instrumentation key
* Uses Arcus secret store to retrieve the connection string
Relates to #620
> feat: add observability v2.5 to worker templates

- src/Arcus.Templates.Tests.Integration/WebApi/Authentication/v1/JwtAuthenticationOptionTests.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Health/v1/HealthEndpointTests.cs
- src/Arcus.Templates.WebApi/Program.cs
Adds an integration test that verifies that we indeed removes the exception details when the application's health is unhealthy.
> test: add integration test for webapi w/ excluded exception in health report

- build/templates/docker-integration-tests.yml
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/Startup.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/AzureFunctionsProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Api/HttpTriggerOrderTests.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Health/HealthChecksTests.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Swagger/SwaggerOpenApiTests.cs
Use the Application Insights' connection string instead of the instrumentation key to setup the Serilog's Application Insights sink in the Azure Functions HTTP trigger project template.
Relates to #620
> feat: use appinsights connectionstring in http trigger

- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Startup.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Startup.cs
- src/Arcus.Templates.ServiceBus.Queue/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Queue/Program.cs
- src/Arcus.Templates.ServiceBus.Topic/.template.config/template.json
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Program.cs
- src/Arcus.Templates.WebApi/.template.config/template.json
- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
- src/Arcus.Templates.WebApi/Program.cs
- src/Arcus.Templates.WebApi/appsettings.json
Rename `Serilog` directive to `Serilog_AppInsights` directive to indicate that the Serilog configuration added to the project with the project option includes Azure Application Insights telemetry logging.
Closes #625
> chore: rename serilog appinsights directive

- src/Arcus.Templates.AzureFunctions.Http/HttpBasedAzureFunction.cs
Adds the `*/*` mediatype to the AcceptsJson check.
Closes https://github.com/arcus-azure/arcus.templates/issues/700
> feat: add mediatype */* to AcceptsJson check

- src/Arcus.Templates.AzureFunctions.Http/local.settings.json
- src/Arcus.Templates.Tests.Integration/AzureFunctions/AzureFunctionsProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/AzureFunctionsDatabricksProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/EventHubs/AzureFunctionsEventHubsProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/AzureFunctionsHttpProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Health/HealthChecksTests.cs
Use `local.settings.json` to set Azure Application Insights connection string so that the Azure Functions HTTP trigger project created from the template can be run directly.
Closes #746
> chore: use `local.settings.json` in Azure Functions HTTP trigger project template

- src/Arcus.Templates.AzureFunctions.Http/local.settings.json
Special characters are getting escaped, which makes it rather strange-looking.
Better to avoid special characters, here.
> chore: don't use special chars in `local.settings.json`

- src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj
launchsettings.json was not added to the webapi project by this.
Relates to #764
> fix: do not exclude launchsettings.json on webApi template

- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Arcus.Templates.AzureFunctions.Databricks.JobMetrics.csproj
- src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/Properties/launchSettings.json
- src/Arcus.Templates.AzureFunctions.EventHubs/Arcus.Templates.AzureFunctions.EventHubs.csproj
- src/Arcus.Templates.AzureFunctions.EventHubs/Properties/launchSettings.json
- src/Arcus.Templates.AzureFunctions.Http/Arcus.Templates.AzureFunctions.Http.csproj
- src/Arcus.Templates.AzureFunctions.Http/Properties/launchSettings.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Arcus.Templates.AzureFunctions.ServiceBus.Queue.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/Properties/launchSettings.json
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Arcus.Templates.AzureFunctions.ServiceBus.Topic.csproj
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/Properties/launchSettings.json
- src/Arcus.Templates.EventHubs/Arcus.Templates.EventHubs.csproj
- src/Arcus.Templates.EventHubs/Properties/launchSettings.json
- src/Arcus.Templates.ServiceBus.Queue/Arcus.Templates.ServiceBus.Queue.csproj
- src/Arcus.Templates.ServiceBus.Topic/Arcus.Templates.ServiceBus.Topic.csproj
- src/Arcus.Templates.ServiceBus.Topic/Properties/launchSettings.json
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/AzureFunctionsDatabricksProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Databricks/JobMetrics/Configuration/LaunchSettingsTests.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/EventHubs/AzureFunctionsEventHubsProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/EventHubs/Configuration/LaunchSettingsTests.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/Http/Configuration/LaunchSettingsTests.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/ServiceBus/AzureFunctionsServiceBusProject.cs
- src/Arcus.Templates.Tests.Integration/AzureFunctions/ServiceBus/Configuration/LaunchSettingsTests.cs
- src/Arcus.Templates.Tests.Integration/Fixture/TemplateProject.cs
- src/Arcus.Templates.Tests.Integration/WebApi/Configuration/LaunchSettingsTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/Configuration/LaunchSettingsTests.cs
- src/Arcus.Templates.Tests.Integration/Worker/ServiceBusWorkerProject.cs
- src/Arcus.Templates.WebApi/Properties/launchSettings.json
Streamline the `/Properties/launchSettings.json` file in all project templates with both a 'Project' and 'Docker' profile to start the resulting project.
Closes #764
> chore: streamline launchsettings in project templates (❗)

- src/Arcus.Templates.AzureFunctions.ServiceBus.Queue/OrderFunction.cs
- src/Arcus.Templates.AzureFunctions.ServiceBus.Topic/OrderFunction.cs
Retrieve the optional `CorrelationId`. This is not used (anymore) for the correlation we use. (The `Diagnostic-Id` application property is used instead).
> chore: optional correlation id retrieval in az func servicebus templates

- README.md
Remove 'Core' in '.NET Core templates' in the `README.md` file.
> chore: remove 'core' in readme
